---
deployment:
  tasks:
    - export APP_DIR="$HOME/repositories/serdadu"
    - /bin/mkdir -p "$APP_DIR"
    - >
      /bin/rsync -a --delete
      --exclude='.git'
      --exclude='.github'
      --exclude='node_modules'
      --exclude='vendor'
      --exclude='.cpanel.yml'
      ./ "$APP_DIR"
    - cd "$APP_DIR"
    - composer install --no-dev --optimize-autoloader
    - php artisan key:generate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan storage:link || true
    - /bin/rsync -a --delete "$APP_DIR/public/" "$HOME/public_html/"
