---
deployment:
  tasks:
    - >
      /bin/bash -lc '
      echo "DEPLOY START: $(date)" >> $HOME/deploy.log
      export APP_DIR="$HOME/repositories/serdadu"
      /bin/mkdir -p "$APP_DIR"
      /bin/rsync -a --delete --exclude=.git --exclude=.github --exclude=node_modules --exclude=vendor --exclude=.cpanel.yml ./ "$APP_DIR" 2>&1 | tee -a $HOME/deploy.log
      cd "$APP_DIR"
      composer install --no-dev --optimize-autoloader 2>&1 | tee -a $HOME/deploy.log
      php artisan key:generate --force 2>&1 | tee -a $HOME/deploy.log || true
      php artisan config:cache 2>&1 | tee -a $HOME/deploy.log || true
      php artisan route:cache 2>&1 | tee -a $HOME/deploy.log || true
      php artisan view:cache 2>&1 | tee -a $HOME/deploy.log || true
      php artisan storage:link 2>&1 | tee -a $HOME/deploy.log || true
      /bin/rsync -a --delete "$APP_DIR/public/" "$HOME/public_html/" 2>&1 | tee -a $HOME/deploy.log
      echo "DEPLOY END: $(date)" >> $HOME/deploy.log
      '